### ISSUE TITLE
Support for SSH keys protected by passphrase

### ISSUE THREAD

**Issue by kwart** [wildfly-extras/sunstone#21]
Internal ID: 50

It's not possible to use SSH key protected by passphrase. Following exception is thrown:

```
java.lang.IllegalStateException: Optional.get() cannot be called on an absent value
  at com.google.common.base.Absent.get(Absent.java:47)
  at org.jclouds.crypto.ASN1Codec.createASN1Sequence(ASN1Codec.java:84)
  at org.jclouds.crypto.ASN1Codec.decodeRSAPrivateKey(ASN1Codec.java:64)
  at org.jclouds.crypto.Pems$DecodeRSAPrivateCrtKeySpec.parseResult(Pems.java:238)
  at org.jclouds.crypto.Pems$DecodeRSAPrivateCrtKeySpec.parseResult(Pems.java:233)
  at org.jclouds.crypto.Pems$PemProcessor.getResult(Pems.java:98)
  at com.google.common.io.ByteSource$ByteArrayByteSource.read(ByteSource.java:532)
  at org.jclouds.crypto.Pems.fromPem(Pems.java:195)
  at org.jclouds.crypto.Pems.privateKeySpec(Pems.java:214)
  at org.jclouds.crypto.Pems.privateKeySpec(Pems.java:252)
  at org.jclouds.ssh.SshKeys.fingerprintPrivateKey(SshKeys.java:211)
  at org.jclouds.openstack.nova.v2_0.compute.strategy.ApplyNovaTemplateOptionsCreateNodesWithGroupEncodedIntoNameThenAddToSet.execute(ApplyNovaTemplateOptionsCreateNodesWithGroupEncodedIntoNameThenAddToSet.java:128)
  at org.jclouds.compute.internal.BaseComputeService.createNodesInGroup(BaseComputeService.java:217)
```

Users hit this on OpenStack, but it can be a general issue.

Workaround exists - to use an unprotected key.

**Comment by istraka** [comment]
This is for 1.x branch which is in a maintenance mode.
