### ISSUE TITLE
Creating instances with AMI name does not work for private images

### ISSUE THREAD

**Issue by LittleJohnII** [wildfly-extras/sunstone#43]
I've tried creating some instances with a private image by supplying the image name and I got:

```
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: No image exists: <<<image-name>>>
    at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[na:1.8.0_45]
    at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[na:1.8.0_45]
    at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1584) ~[na:1.8.0_45]
    at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1574) ~[na:1.8.0_45]
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[na:1.8.0_45]
    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[na:1.8.0_45]
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[na:1.8.0_45]
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[na:1.8.0_45]
Caused by: java.lang.IllegalArgumentException: No image exists: <<<image-name>>>
    at org.wildfly.extras.sunstone.api.impl.ResolvedImage.fromNameAndId(ResolvedImage.java:49) ~[sunstone-core-0.8.0.jar:na]
    at org.wildfly.extras.sunstone.api.impl.ec2.EC2Node.<init>(EC2Node.java:61) ~[sunstone-core-0.8.0.jar:na]
    at org.wildfly.extras.sunstone.api.impl.ec2.EC2CloudProvider.createNodeInternal(EC2CloudProvider.java:73) ~[sunstone-core-0.8.0.jar:na]
    at org.wildfly.extras.sunstone.api.impl.AbstractJCloudsCloudProvider.lambda$createNode$3(AbstractJCloudsCloudProvider.java:100) ~[sunstone-core-0.8.0.jar:na]
    at org.wildfly.extras.sunstone.api.impl.AbstractJCloudsCloudProvider$$Lambda$22/346631962.apply(Unknown Source) ~[na:na]
    at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853) ~[na:1.8.0_45]
    at org.wildfly.extras.sunstone.api.impl.AbstractJCloudsCloudProvider.createNode(AbstractJCloudsCloudProvider.java:95) ~[sunstone-core-0.8.0.jar:na]
    at org.wildfly.extras.sunstone.api.impl.AbstractJCloudsCloudProvider.lambda$createNodeAsync$6(AbstractJCloudsCloudProvider.java:154) ~[sunstone-core-0.8.0.jar:na]
    at org.wildfly.extras.sunstone.api.impl.AbstractJCloudsCloudProvider$$Lambda$21/898695324.get(Unknown Source) ~[na:na]
    at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1582) ~[na:1.8.0_45]
    ... 5 common frames omitted
```

Creating the instance via ID succeeds and the logs show that the image name is indeed correct.

I'm not sure why this is happening or whether there is some solution to it.

**Comment by istraka** [comment]
Our current tests in cloud ts doesn't seem to have problem with private AMI.
