### ISSUE TITLE
Deployment fails on EC2 node

### ISSUE THREAD

**Issue by tommaso-borgato** [wildfly-extras/sunstone#99]
When deploying on a EC2 node created using RED HAT AMI, we get the following error:

```
2022-03-07 09:55:21,447 ERROR [org.jboss.as.controller.management-operation] (management-handler-thread - 1) WFLYCTL0013: Operation ("add") failed - address: ({"deployment" => "ROOT.war"}): java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
	at java.util.ArrayList.get(ArrayList.java:435)
	at java.util.Collections$UnmodifiableList.get(Collections.java:1311)
	at org.jboss.as.controller.OperationContextImpl.getAttachmentStream(OperationContextImpl.java:251)
	at org.jboss.as.server.deployment.DeploymentHandlerUtils.getInputStream(DeploymentHandlerUtils.java:96)
	at org.jboss.as.server.deployment.DeploymentAddHandler.addFromContentAdditionParameter(DeploymentAddHandler.java:217)
	at org.jboss.as.server.deployment.DeploymentAddHandler.execute(DeploymentAddHandler.java:138)
	at org.jboss.as.controller.AbstractOperationContext.executeStep(AbstractOperationContext.java:1040)
	at org.jboss.as.controller.AbstractOperationContext.processStages(AbstractOperationContext.java:779)
	at org.jboss.as.controller.AbstractOperationContext.executeOperation(AbstractOperationContext.java:468)
	at org.jboss.as.controller.OperationContextImpl.executeOperation(OperationContextImpl.java:1415)
	at org.jboss.as.controller.ModelControllerImpl.internalExecute(ModelControllerImpl.java:431)
	at org.jboss.as.controller.ModelControllerImpl.lambda$execute$1(ModelControllerImpl.java:248)
	at org.wildfly.security.auth.server.SecurityIdentity.runAs(SecurityIdentity.java:304)
	at org.wildfly.security.auth.server.SecurityIdentity.runAs(SecurityIdentity.java:270)
	at org.jboss.as.controller.ModelControllerImpl.execute(ModelControllerImpl.java:248)
	at org.jboss.as.controller.remote.ModelControllerClientOperationHandler$ExecuteRequestHandler.doExecute(ModelControllerClientOperationHandler.java:240)
	at org.jboss.as.controller.remote.ModelControllerClientOperationHandler$ExecuteRequestHandler.access$400(ModelControllerClientOperationHandler.java:138)
	at org.jboss.as.controller.remote.ModelControllerClientOperationHandler$ExecuteRequestHandler$1$1.run(ModelControllerClientOperationHandler.java:162)
	at org.jboss.as.controller.remote.ModelControllerClientOperationHandler$ExecuteRequestHandler$1$1.run(ModelControllerClientOperationHandler.java:158)
	at org.wildfly.security.auth.server.SecurityIdentity.runAs(SecurityIdentity.java:328)
	at org.wildfly.security.auth.server.SecurityIdentity.runAs(SecurityIdentity.java:285)
	at org.jboss.as.controller.AccessAuditContext.doAs(AccessAuditContext.java:254)
	at org.jboss.as.controller.AccessAuditContext.doAs(AccessAuditContext.java:225)
	at org.jboss.as.controller.remote.ModelControllerClientOperationHandler$ExecuteRequestHandler$1.execute(ModelControllerClientOperationHandler.java:158)
	at org.jboss.as.protocol.mgmt.ManagementRequestContextImpl$1.doExecute(ManagementRequestContextImpl.java:70)
	at org.jboss.as.protocol.mgmt.ManagementRequestContextImpl$AsyncTaskRunner.run(ManagementRequestContextImpl.java:160)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:513)
```

the deployment is  `/tmp/ROOT.war` and belongs to user `ec2-user`

EAP runs with used `jboss`.

when performing the deployment with the root user it succeeds.

**Comment by istraka** [comment]
Do you mean performing CLI operation using `OnlineManagementClient`? If so, have you tried `Deploy` command [1]?

[1] https://github.com/wildfly-extras/creaper/blob/master/commands/src/main/java/org/wildfly/extras/creaper/commands/deployments/Deploy.java

**Comment by istraka** [comment]
Due to inactivity, I am closing the issue.
